//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plagiarism.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
        public Nullable<int> UploaderId { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public bool Status { get; set; }
        public string StatusDetails { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
